USE [master]
GO

/****** Object:  Database [TCLOAN]    Script Date: 13-5-2018 19:49:30 ******/
CREATE DATABASE [TCLOAN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TCLOAN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TCLOAN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TCLOAN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TCLOAN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TCLOAN] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TCLOAN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TCLOAN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TCLOAN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TCLOAN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TCLOAN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TCLOAN] SET ARITHABORT OFF 
GO

ALTER DATABASE [TCLOAN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TCLOAN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TCLOAN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TCLOAN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TCLOAN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TCLOAN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TCLOAN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TCLOAN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TCLOAN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TCLOAN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TCLOAN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TCLOAN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TCLOAN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TCLOAN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TCLOAN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TCLOAN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TCLOAN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TCLOAN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TCLOAN] SET  MULTI_USER 
GO

ALTER DATABASE [TCLOAN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TCLOAN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TCLOAN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TCLOAN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TCLOAN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TCLOAN] SET QUERY_STORE = OFF
GO

USE [TCLOAN]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TCLOAN] SET  READ_WRITE 
GO

