USE [master]
GO

/****** Object:  Database [TTR-MDCS]    Script Date: 13-5-2018 19:49:11 ******/
CREATE DATABASE [TTR-MDCS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TTR-MDCS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TTR-MDCS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TTR-MDCS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TTR-MDCS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TTR-MDCS] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TTR-MDCS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TTR-MDCS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TTR-MDCS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TTR-MDCS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TTR-MDCS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TTR-MDCS] SET ARITHABORT OFF 
GO

ALTER DATABASE [TTR-MDCS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TTR-MDCS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TTR-MDCS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TTR-MDCS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TTR-MDCS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TTR-MDCS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TTR-MDCS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TTR-MDCS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TTR-MDCS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TTR-MDCS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TTR-MDCS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TTR-MDCS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TTR-MDCS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TTR-MDCS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TTR-MDCS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TTR-MDCS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TTR-MDCS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TTR-MDCS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TTR-MDCS] SET  MULTI_USER 
GO

ALTER DATABASE [TTR-MDCS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TTR-MDCS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TTR-MDCS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TTR-MDCS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TTR-MDCS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TTR-MDCS] SET QUERY_STORE = OFF
GO

USE [TTR-MDCS]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TTR-MDCS] SET  READ_WRITE 
GO

